- README.md
- package-lock.json
- package.json
- src/dom.js
- test/dom.test.js
XML to JSON transformation uses the following heuristic. When an XML element has several children with the same name, it consider it to be an array. If there's only one child with a given name, the situation is ambiguous: is it a child element or a child array of 1 element.
Collections can be identified with a better heuristic because the parent name ends with "-collection". In this case, we'll always assume that children are an array.
For instance, with the previous heuristic
```
<root><elem id="1"></root> => { elem: { "@id": "1" } }
<root><elem id="1"><elem id="2"></root> => { elem: [ { "@id": "1" } , { "@id": "2" } ] }
```
With the new heuristic, this is only changed for elements whose name ends with "-collection"
```
<root><elem id="1"></root> => { elem: { "@id": "1" } }
<root><elem …
```
> Issue #1 - Query in select mode should always return an array, even if result is empty or one one row

- .github/workflows/npm-publish.yml
Add github action to automatically tag and publish to npm.
Now, when someone changes the version in package.json to 1.2.3 and pushes a commit with the message Release 1.2.3, the npm-publish action will create a new tag v1.2.3 and publish the package to the npm registry.
See https://github.com/marketplace/actions/publish-to-npm
> Publish-to-npm action

- .gitignore
- README.md
- package-lock.json
- package.json
- src/client.js
- src/methodCache.js
- src/soap.js
- test/caches.test.js
* Support for int64 type (represented as a string to avoid rounding errors)
* Fix issue with the SoapAction header for interface methods. When calling a method which is defined on an interface (for instance xtk:persist), the SoapAction
header must use the interface id and not the schema id. For instance, when one calls the xtk:session Write method, one should call NLWS.xtkSession.Write, but
the SoapAction header must be "xtk:persist#Write" and not "xtk:session#Write" for the call to complete successfully. In older SDK versions, one had to call
NLWS.xtkPersist.Write which would only work if the xtk:persist interface schema was cached before. As there's no xtk:schema entity for the interfaces, the only
way to cache such an interface is to have previously called a method on xtk:session. This …
> Release 0.1.23

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- samples/000 - basics - logon.js
- src/client.js
- src/index.js
- src/soap.js
- src/transport.js
- test/client.test.js
- test/index.test.js
- test/soap.test.js
* Added the `sdk.ip()` function to retreive the ouptbound IP to be whitelisted to access Campaign
* New `ofSecurityToken` authentication method for the client-side SDK, which can be used to log on with a security token only. The session token will be passed automatically by the browser.
> Release 1.0.3

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/application.js
- src/campaign.js
- src/client.js
- src/crypto.js
- src/domUtil.js
- src/entityAccessor.js
- src/index.js
- src/methodCache.js
- src/optionCache.js
- src/soap.js
- src/transport.js
- src/util.js
- src/xtkCaster.js
- src/xtkEntityCache.js
- test/caches.test.js
- test/client.test.js
- test/mock.js
- test/soap.test.js
- test/util.test.js
* Fix an issue in the logon() function which was not always returning a promise. Some authentication methods such as SessionToken we returning synchronously. Made it so that logon always returns a promise. This should not be a breaking change as logon does not actually return a value
* Refactor caches (Options cache, Schemas cache, and Methods cache) to use a generic cache class
* Make sure options parameter of ConnectionParameters constructor is not modified
* Added a persistent cache for schemas, methods, and options using the browser localStorage by default
* Make sure X-Security-Token header is hidden as well as session token cookies
* Added jshint configuration and fixed warnings reported by jshint
* Fixed vulnerability in ansi-regex; upgrade jest-junit to version 13 to fix
* Small …
> Release 1.0.5

- src/application.js
- test/application.test.js
Add enum attribute to xtkSchemaNode
> Adding enum attribute

- README.md
- src/campaign.js
- src/client.js
- src/soap.js
- test/client.test.js
- test/soap.test.js
Retry SOAP call when the session is expired.
An asyn refreshClient callback must be defined that refresh the SDK client.
Below an example:
`const connectionParameters = sdk.ConnectionParameters.ofUserAndPassword(
url, "admin", "admin",
{refreshClient: async (client)=>{
await client.logon();
return client;
}
});`
Unit tests.
> Run a call back when the session token is expired

- samples/002 - basics - schemas.js
- samples/020 - encryption.js
- test/client.test.js
- test/crypto.test.js
- test/mock.js
After enabling codeQL scanning, a few alerts were reported.
* Hardcoded secrets in the test. This was not really an issue as the hardcoded secret is only for tests. This was changed to generate a secret for each test
* Improper code sanitization. Another false alert where the code scanner was thinking we were using string concatenation to generate HTML. In fact, it was not HTML, but a log string with looks like ">> ..... => ${...}`. I suppose the presence of the => is where the scanner was led into thiking we're generating HTML. So changed it to ":"
> Fix code scanning alerts. Remove hardcoded secrets

- CHANGELOG.md
- MIGRATION.md
- README.md
- package-lock.json
- package.json
- src/application.js
- src/index.js
- src/util.js
- src/xtkCaster.js
- test/application.test.js
- test/client.test.js
- test/util.test.js
Changes in the metadata api (`application.getSchema`) which was not completely implemented. While this API is meant to be largely compatible with the [ACC JS API](https://docs.adobe.com/content/help/en/campaign-classic/technicalresources/api/c-Application.html), it's not always possible to do so because of the asynchronous nature of the SDK. The JS API is executed inside the Campaign application server can will synchronously and transparently fetch schemas as needed. Howerer the SDK runs outside of the Campaign server. It will synchronously and transparently fetch schemas as needed, but this will be done adynchronously. 
Differences are document in the `Application` section of the README.
* Provide array and map access to XtkSchemaKey.fields, 
* The order of children of a node has been …
> Release 1.1.0

- CHANGELOG.md
- README.md
- package.json
- src/client.js
- src/soap.js
- test/client.test.js
- test/soap.test.js
Release 1.1.1 - Fixed an issue with encoding: make the default charset encoding to be UTF-8.
See https://github.com/adobe/acc-js-sdk/issues/26
> Release 1.1.1 - Fixed an issue with charset encoding

- CHANGELOG.md
Add support for choosing the representation (XML or JSON) at the method level using NLWS.xml or NLWS.json.
The client object is created with a default representation which is used for all API calls in the context of this client. Since version 1.1.2, it is also possible to set the representation at the method level, i.e. use a particular representation for a particular API call.
client.NLWS: use the default representation set at the client level
client.NLWS.xml: use the XML reresentation
client.NLWS.json: use the SimpleJson representation
> Release 1.1.2 Bump version to 1.1.2

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- samples/utils.js
- src/client.js
- src/soap.js
- test/client.hasPackage.test.js
- test/client.test.js
- test/soap.test.js
Release 1.1.3
* Fix a bug in client.hasPackage which was returning an incorrect result when passed a single parameter (it would always return false). Fixed the corresponding unit test too.
* Fix a bug causing API calls having a input parameter of type "int" to fail. Usually the type is described as "long", but sometimes "int" is used instead, such as, for instance, in the nms:extAccount#UpdateMCSynchWkf method.
* When using XML representations and DOMDocument method parameter type, the SDK expects to be passed an actual DOM document. Now it supports being passed a DOM element too. This is a common case when using the nms:delivery#createFromModel API followed by a xtk:session#Write API call.
* Avoid the error 'Cannot transform entity to xml because no XML root name was given' by using SOAP …
> Release 1.1.3

- CHANGELOG.md
- README.md
- src/application.js
- src/cacheRefresher.js
- src/client.js
- test/application.test.js
- test/cacheRefresher.test.js
- test/caches.test.js
- test/client.test.js
* Make registerCacheChangeListener / unregisterCacheChangeListener / callAndRefresh, refresh private (rename with _ prefix)
* Fix a few typos and make sure JsDoc is complete
* Simplify CacheRefresher constructor (remove connectionParameters argument)
* Restore deleted tests for application object
* Fixes a few compilation warnings in cache refresher tests
* Added test for cache remove function: make sure key can be safely removed twice
* Fixed errors and compilation warnings in client.tests
* Fixed linting errors
> * Added documentation about auto-refresh caches

- .eslintrc.js
- CHANGELOG.md
- README.md
- compile.js
- package-lock.json
- src/application.js
- src/cache.js
- src/cacheRefresher.js
- src/client.js
- test/application.test.js
- test/cacheRefresher.test.js
- test/caches.test.js
- test/client.test.js
- test/mock.js
Send a query to acc nlserver server every 10 seconds to check if an entities has been modified.
Change on schema are not visible : if a schema is extended , the extension is not visible the old version of the schema is still present
If an entity is modified we have to wait 5 minutes before seeing the change or change is never saw because there is no refresh  behavior
Manual test with the new web ui, with a index.js page.
> Refresh cache when entities are modified

- README.md
- package-lock.json
- src/cache.js
- src/cacheRefresher.js
- src/client.js
- test/caches.test.js
- test/observability.test.js
Add a mechanism for observability in the SDK. We do not want to depend on any observability framework. Instead, we use the observer mechanism available in the SDK to notify a callback function of internal SDK events, such as soap calls, cache refreshes, etc.
The idea is that a client app can register to those events, and format them / send them to whatever observability framework they want.
See the #Observers section of the README file for more details.
In addition, we've added statistics to all caches, keeping track of how many reads, writes, hits, etc.
> Observability

- CHANGELOG.md
- README.md
- src/application.js
- test/application.test.js
Add translation ids when building XtkSchema, XtkSchemaNodes, XtkEnumeration and XtkEnumerationValue in order to by the intl library for translation.
In acc web ui schema is still in English for changing the language.
to have the schema content localized
added unit tests
Tested on web ui side.
> Add id to Schema for globalization

- src/application.js
Schemas attributes and element have a "belongsTo" attribute which indicates in which source schema this attribute or element was initially declared. This can be used to detect if an attribute is an extension, and if it is a custom attribute.
> Support for belongsTo attribute indicating custom/extended schema

- src/soap.js
- test/soap.test.js
If Delivery preparation job logs queryDef response contains session expiration error string as a log error message then the old code consider that the SOAP response is on error which is not correct.
The fixe checks the session expiration error only when the response is not an XML (Raw text).
> NEO-50592 : Correction of a false positive session expiration error

- src/application.js
- test/application.test.js
Do not set a localization id when label is not set , same for description and singular label.
When try to use localization id of a label or a description  in a schema that was implicit set because it does not exist, an error message is logged.
Avoid to log an error message for each implicit set description or label.
Unit test and test in context of the acc web ui.
> NEO-50308: no localization id when no label

- src/application.js
- test/application.test.js
Expose attribute instanceLocale in CurrentLogin
Ability to get the acc server instance locale to get default label in the locale of the server
Help to check if a OOTB default label has been changed
unit test
test in web ui
> NEO-51219: expose attribute instanceLocale in CurrentLogin

- src/client.js
- test/client.test.js
`client._makeHttpCall` API needs the property passed as `data` instead of `body`. Fixing that in file upload.
Bug fix
File upload doesn't work.
Modified a test to detect the issue.
Tested acc-js-sdk in a browser.
> File upload: Replace incorrect property body with data passed to _makeHttpCall

- docs/application.html
- test/application.test.js
Some ACC attributes are defined as both xml & sql
```
<attribute name="seedProcessed" type="long" label="Seed addresses" desc="Number of seeds inserted" sql="true" xml="true"/>
```
This adds a test to make sure the SDK properly handles such nodes: both isSQL and isMappedAsXml should return true.
New unit test with the nms:delivery/properties/@seedProcessed which is an actual node mapped as both sql and xml
> Add unit test for schema nodes which are mapped as both xml and sql

- docs/changeLog.html
- src/client.js
- test/client.test.js
- test/mock.js
This method starts with a lower case letter (unlike other methods which start with an upper case) which was not propertly handled by the SDK
Calling
`client.NLWS.nmsSeedMember.getAsModel('', 'XX', selection, {}))``
was failing with error SDK-000009 Unknown method 
New unit test
> Fix a bug calling the nms:seedMember#getAsModel method. 

- src/client.js
- src/transport.js
- test/client.test.js
Authenticate using 'X-Session-Token' header for file upload and reports
Currently, file upload and reports API use cookies for authentication. Migrating to custom headers as it will allow to integrate the acc-js-sdk in a browser as third-party cookies will not be readable.
* This feature is experimental. Longer term, the requests will support Adobe IMS access tokens.
* Remove `__sessiontoken` cookie hack.
* Credentials needn't be passed in CORS requests.
* Modify unit tests accordingly.
- Modified unit tests to test additional capability.
- Manual tests (using `curl` requests)
> Authenticate using 'X-Session-Token' header for file upload and reports

- docs/changeLog.html
- docs/simpleJson.html
- src/domUtil.js
- src/util.js
- test/client.test.js
- test/domUtil.test.js
- test/util.test.js
I discovered a few more issues in the XML to JSON serialization.
More documentation: https://opensource.adobe.com/acc-js-sdk/simpleJson.html
when XML element has both a text content and attributes or child elements
when root element has only text
when XML element has both an attribute and a child element with the same name
when array contains element which only have text
when XML is formatted (and therefore has insignificant whitespaces)
XML collections (i.e. when root node ends with “-collection”) would sometimes contain a JSON property “#text”
So far the SimpleJSon rules where:
XML Attributes are transformed to JSON properties without the “@” prefix. The rationale is that Campaign generally uses attributes, so we make the attribute syntax the most straightforward.
XML Elements are …
> NEO-51318: fix SimpleJson serialization issues

- compile.js
- docs/_data/navigation.yml
- docs/xtkInterface.html
- docs/xtkJob.html
- src/client.js
- src/util.js
- src/xtkJob.js
- test/mock.js
- test/util.test.js
- test/xtkJob.test.js
The xtk:jobInterface is not currently supported by the SDK. The reason is that job entities do not implement xtk:jobInterface (they implement xtk:job) and job interface methods are therefore not visible to the SDK.
The SDK now provides the client.jobInterface function which returns an object which can be used to submit jobs, retreive their status, progress, logs, etc. See the documentation of the SDK for more details.
Long running jobs such as nms:delivery#Prepare must be run as jobs
* New unit test for all new code
* Actually tested on local instance
> NEO-51282: Add support for xtk:jobInterface methods

- docs/observability.html
- src/cacheRefresher.js
- src/campaign.js
- src/client.js
- src/soap.js
- test/client.test.js
- test/mock.js
- test/observability.test.js
- test/soap.test.js
Add an interception mechanism to make it possible for an observer to modify SOAP call parameters before making the SOAP calls and modify return values before they are returned to the caller
In order to have a central place to properly intercept call, some refactoring has been done.
The central place to make SOAP calls is the _makeInterceptableSoapCall function.
This function is in charge of calling the beforeSoapCall and afterSoapCall observers, and to serialize and deserialize the XML into the expected representation. This code was inlined in _callMethod before, it's now more structured and split into multiple functions (_writeSoapCallParameters, _makeSoapCall, and _readSoapCallResult). The XtkMethodParam type is also introduced to represent a parameter of a SOAP call.
A side effect of …
> Add onBeforeCall / onAfterCall observers

- src/soap.js
- test/client.test.js
- test/soap.test.js
For troubleshooting purpose, the SDK is adding a query parameter with the API call URN (schema and method) to the soap router end point. This was not correctly URL encoded, which can cause problems in some cases. Now the query parameter is properly encoded.
Normal SOAP URL: https://myinstance.com/nl/jsp.soapRouter.jsp
Previous URL (not properly encoded): https://myinstance.com/nl/jsp.soapRouter.jsp?xtk:session:Empty
New URL (properly encoded): https://myinstance.com/nl/jsp.soapRouter.jsp?soapAction=xtk%3Asession%23Empty
The new encoding (potentially breaking change) is a query parameter named soapAction which contains the encorde URN of the SOAP call.
Unit tests
Instance which was causing problems
> Fix encoding of the soapRouter URL parameters

- src/client.js
- test/client.test.js
When creating a new "Client" object, we check in the storage if there're some irrelevant acc.js.sdk cache items: containing other sdk versions or cache for other instances.
in the case of using localStorage, whose size is limited to 5Mb, the irrelevant caches take space
A unit test has been added
> Clear storage cache if the sdk versions or the instances are different

- src/client.js
- src/soap.js
- src/util.js
- test/soap.test.js
- test/util.test.js
Make sure all SOAP API calls set the custom X-Session-Token header. This change is necessary to ensure consistent and secure authentication when the SDK is used in the context of a browser (where cookies can be blocked) with future server-side changes.
Third-party Cookies are blocked by the browsers, which means SOAP call authentication relies on the session token passed in the SOAP payload. Unfortunately this requires an ACC security zone with sessionTokenOnly flag set which is not a secure configuration. Instead, we pass the session token as an HTTP header and future builds of the server will be able to handle it in secure security zones.
Ensure secure access by default
Unit tests
> Add the X-Session-Token custom header to all SOAP and API calls

- docs/caches.html
- docs/changeLog.html
- src/cache.js
- src/cacheRefresher.js
- src/client.js
- src/methodCache.js
- src/optionCache.js
- src/util.js
- src/xtkEntityCache.js
- test/cacheRefresher.test.js
- test/caches.test.js
- test/client.test.js
- test/observability.test.js
- test/util.test.js
Make the cache interface asynchronous. See https://opensource.adobe.com/acc-js-sdk/caches.html for more details.
The storage interface is backwards compatible: getItem, setItem, and removeItem can be synchronous functions. They can also be asynchronous, i.e. return promises.
There is however a slight change in the client API concerning the cache clearing APIs which are now returning a promise, i.e. the cache clearing is made asynchronously.
This concerns the functions: clearOptionCache, clearMethodCache, clearEntityCache, and clearAllCaches
Support storages which have an asynchronous interface.
Unit tests
The change is largely non breaking, except for the cache clearing functions.
> Make the caches asynchronous

- docs/application.html
- src/application.js
- src/cacheRefresher.js
- test/application.test.js
Extended XtkSchemaNode class with additional dbEnum property
Adde dbENum property to XtkSchemaNode since it was missing
New Unit test
> NEO-49613: Added dbEnum to XtkSchemaNode

- src/application.js
- test/application.test.js
Add support of attribute `default` and element `<default>`
Schemas can provide default values for scalar fields or collections. This PR handles the required items to extract these default values.
Required by ACC Web UI
Unit tests.
> NEO-55996: Add support of default / <default>, required to handle default values of schema items

- src/client.js
- test/client.test.js
New optional action parameter for upload function. This parameter can be used to set the post-processing action to execute after upload. Defaults to 'publishIfNeeded'. Also supports 'none' which will execute no action
Current implementation of upload function will automaticaly publish the uploaded resource as a public resource in Campaign. This is correct for attachments, or public resources used in email, but is not correct for other type of resoures, for instance an uploaded audience.
The default value (i.e. no action given) defaults to a pubish action for backwards compatibility
Work in progress to support upload functionality.
Unit tests
> New optional action parameter for upload function

- src/domUtil.js
- src/util.js
- test/domUtil.test.js
Fixed a bug causing incorrect JSON to XML transformation when the JON object has a property named 'length'
In the following JSON object, there's an "attribute" object with a property named "length"
```
const json = {
element: {
attribute: {
length: "256",
name: "id",
},
}
};
```
Converting such an object to XML fails or does not return the expected result because an internal conversion function uses the existence of the "length" property to test if a JS object is an array In this example, "attribute" is considered an array since it has a "length" attribute. However, in this case "length" is just an XTK attribute which happens to be named 'length'. This attribute exists on schemas for example.
Now using Array.isArray javaScript function to safely test the type of an object to be an array. …
> Fixed a bug causing incorrect JSON to XML transformation when the JSON object has a property named 'length'

- src/domUtil.js
- test/domUtil.test.js
The content of HTML deliveries is returned as an XML CDATA node. Sometimes this content itself may contain CDATA elements. Campaign will "escape" such content as follow:
/*<![CDATA[*/ @import url("https://fonts.googleapis.com/css?family=Lato|Open+Sans");[style*="Lato"]{font-family:Lato,Arial,sans-serif!important}[style*="Open Sans"]{font-family:Open Sans,Arial,sans-serif!important}/*]]]><![CDATA[]>*/
When the SDK tried to convert XML to JSON, it has the following logic:
* (1) If a XML element has a unique text child (text or cdata type), it will generate a JSON property starting with the element name prefix with "$". For instance <title><![CDATA[Hello]]></title> will be converted to $title: "Hello".
* (2) However, if there are multiple children, it will generate a JSON object with a "$" …
> Consider elements with multiple text children as if they had one single text child

- src/application.js
- src/util.js
- test/application.test.js
Some enumerations such as xtk:dataTransfer:decimalCount are a little bit special.
* They are of numeric type (baseType=short in this case)
* They have several enum values for which the "value" is not defined (only "name" is defined)
* The "name" property of enumeration values may be a stringified number (ex: "0")
This cause a problem loading schemas since enumeration values are indexed in an array map as both a map (indexed by enum name) and as an array (indexed by the order of apperance of value elements). 
In this example, the first value (with name "all") is indexed with index 0 (as it is the first one), and the second value is indexed with name "0" which collides with the previous and causes an error.
```
<enumeration name="decimalCount" basetype="short">
<value value="-1" name="all" …
```
> Support for xtk:dataTransfer:decimalCount enumeration

- src/application.js
- test/application.test.js
Handle a new schema item translatedDefault. Required to implement workflow split activity
Handle an element schema not taken in account.
Required to implement split activity.
Unit test included in the PR.
> NEO-54340: Handle translatedDefault element of XTK schemas

- src/application.js
- test/application.test.js
Allow duplicated enum values in schemas
Fix issue in temp schema generated in the workflow with an enrichement activity
An example of a schema taht contents a duplicated enum value e029d4880:
```xml
<extension xmlns="urn:xtk:queryDef" label="Enrichment : get last 2 products bought" mappingType="sql" name="enrich" namespace="temp">
<enumeration basetype="string" name="e029d4880">
<value desc="Computer" label="Computer" name="computer" value="computer"/>
<value desc="Watch" label="Watch" name="watch" value="watch"/>
</enumeration>
<enumeration basetype="string" name="e029d4880">
<value desc="Computer" label="Computer" name="computer" value="computer"/>
<value desc="Watch" label="Watch" name="watch" value="watch"/>
</enumeration>
<element advanced="false" label="Enrichment : get last 2 …
```
> NEO-63455: allow duplicated enum values

- src/client.js
The change done in https://github.com/adobe/acc-js-sdk/pull/91 didn't work correctly when sdk is used inside browser.
Noticed that we have two different implementations of transport layer - axios(node) & fetch(browser).
I didn't knew that earlier & had only tested with a nodejs app.
Two issues -
- Axios automatically serialized json body but fetch doesn't.
- Axios handled to return json response while fetch handled for string response.
ttps://github.com/adobe/acc-js-sdk/pull/91
same as linked PR
> fix bug in uploadAemAsset when used through browser

- test/client.test.js
add test for code added in https://github.com/adobe/acc-js-sdk/pull/93
https://github.com/adobe/acc-js-sdk/pull/93
It makes client.js test coverage back to 100%
npm i
npm run unit-tests
> add tests for string response in uploadAemAsset

- src/application.js
- test/application.test.js
set description localization id equals to label localization id when description is empty in source schema and is set to label 
in web ui the description of attributes without description in the source schema is displayed in English even if the language is not English
it fixes attributes description localization
unit test
test in web ui with a modified version of the SDK
Before:
After:
> NEO-62405: set description localization id when description is empty

- docs/_data/navigation.yml
- docs/anonymous.html
- src/client.js
- test/client.test.js
Calling anonymous SOAP methods with the SDK does not work. The reason is that the SDK needs access to schemas to get SOAP method descriptions. As schema access requires authentication, it's not possible to call anonymous SOAP calls.
See documentation here: https://opensource.adobe.com/acc-js-sdk/anonymous.html
https://github.com/adobe/acc-js-sdk/issues/96
More unit tests
> #96 - Support calling anonymous SOAP calls

- src/client.js
- test/client.test.js
The QueryDef result for temporary schema is incorrect for empty results:
In case of a workflow we have the output : { 'workflow:1047471_query2_result': [] } 
instead of { 'workflow_1047471_query2_result': [] }
[NEO-67140](https://jira.corp.adobe.com/browse/NEO-67140)
The change is fixing an issue when doing a preview of a workflow transition 
- This has been test manually
- Unit test is added to the PR
> NEO-67140: fixing schemaName when the queryDef result is empty

- src/client.js
IFrame is an inline element. Giving just height and width without the display won't work. So, adding display property and also adding a unique className for identification.
Multiple iframes are rendered on UI for uploads and these iframes are taking up empty space provided by default by the browser.
Tested it on ACC UI to see if IFrame is no more taking up empty space. Also classname can be seen.
> Adding class name to uploader frame for unique identification

- src/client.js
- src/xtkJob.js
- test/xtkJob.test.js
- fix a bug when calling async getMethod in cache
- support static method in SubmitSoapCall
> NEO-68882: support static method in SubmitSoapCall

- src/application.js
add two attributes "ordered" and "doesNotSupportDiff" for XtkSchemaNode
> Support attributes 'ordered' and 'doesNotSupportDiff' for XtkSchemaNode

- src/xtkJob.js
- test/xtkJob.test.js
Covered the scenarios where the various operations on the XtkJobInterface can be performed with provided jobId.
**UseCase**
User submits a job to perform some async operation and refreshes the browser. Now in order to show the status of the job to the user, we need a way to get the status based on the jobId.
User submits an async Job with a jobId.
```
const job = await client.jobInterface({
xtkschema: <Schema>,
method: <Method>,
jobId:<JobID>,
args: <Arguements>,
});
await job.submitSoapCall();
```
With the implementation in PR, the status of the job with <JobId> can be fetched as mentioned below.
``` 
const job = new XtkJobInterface(client, { jobId: <JobID> }) 
await job.getStatus();
```
Added unit tests
> Add support to execute job operations based on provided jobId

- src/client.js
- src/xtkJob.js
- test/client.test.js
- test/xtkJob.test.js
The extraHttpHeaders passed to the connection parameters which is used to initialise the client, is not present in the XtkJobInterface's function and FileUploader APIs
```
const connectionParameters = sdk.ConnectionParameters.ofBearerToken(targetDomain, imsToken, {extraHttpHeaders: {testHeader: 'headerValue'}});
const clientSdk = await sdk.init(connectionParameters).catch(() => false);
await clientSdk.logon();
const job = await clientSdk.jobInterface({
xtkschema: "nms:dataModel",
method: "write",
jobId: name,
args: dataModelJSON,
});
// This API call does not have the extraHttpHeaders in the headers.
await job.submitSoapCall();
```
Also, the submit and execute APIs does not have the extraHttpHeaders in the header.
Although, all the other methods like getStatus, getResult, cancel, pause, …
> [NEO-78835]: fix extraHttpHeaders issue

- src/client.js
- test/client.test.js
Currently the API will not throw back an error if the publishIfNeeded function fails or its URL gets blocked, which causes an infinite loop on uploading a file in Federated Databases. We needed to add a try and catch block in order to handle these uhnadled exceptions, which I added in this PR.
The issue has ben tested on FAC, where we now get an error toast shown instead of falling into an infinite loop
> [NEO-79113]: Show error toast when file upload API fails

- src/domUtil.js
- test/domUtil.test.js
Before this fix, DOM setAttribute function could crash if name starts with '@' character, which is a forbidden starting character (https://www.w3.org/TR/REC-xml/#NT-NameStartChar)
> Fix domUtil.fromJSON for attributes name starting by invalid at character

- docs/changeLog.html
- package-lock.json
- src/client.js
- test/client.test.js
- test/mock.js
GetEntityIfMoreRecent supports schema ids starting with "xdm:"
Modify the SDK so that the getSchema API call supports them
Example
getSchema("xdm:tenant:unions|xdm.context.profile_union")
getSchema("xdm:audience|ejfwtu349tu0");
This is only supported in "Campaign Orchestration" product and not in ACC.
> Xdm schemas

- docs/changeLog.html
- docs/connectionParameters.html
- src/client.js
- test/client.test.js
Optimization of the ACC JS SDK to handle multi-tenant access.
In multi-tenant deployments of ACC, the access URL is shared across multiple ACC instances. Each instance must have its own caches (schemas, options, etc.) but we use a string derived from the access URL as the cache key.
This does not work in a multi-tenant deployment
UX slowness
Inability to use cache
Corrupted data
Improve User experience (page load speed) in the context of Orchstrated Campaigns
New Unit tests
- [] All new and existing tests passed.
> New instanceKey connection parameter can be used to configure the cache key

- src/client.js
- src/util.js
- test/client.test.js
- test/util.test.js
For some reason the "const counter = await client.NLWS.xtkCounter.increaseValue( { name: 'xtkResource' } );" does not increase the value of the counter which results in the creation and the update of the 'RES1' fileResource.
The problem is that if the RES1 already exists in a folder the user does not have writing rights it results in an error.
The solution that has been decided was have a filename of 'WUI-[uuid]' to ensures unicity.
https://jira.corp.adobe.com/browse/NEO-88828
With this fix, the fileResource created will be in the default folder where the user has writing right.
Only if there is no such folder then the upload will fail (as intended)
New autotest has been added and existing autotest has been modified.
> NEO-88828: fix Acrites upload.

- src/application.js
- src/client.js
- test/application.test.js
- test/client.test.js
Add a new withoutCache parameter to Client.getSchema() and Application.getSchema() methods, allowing developers to bypass the cache and fetch schemas directly from the server.
https://jira.corp.adobe.com/browse/NEO-85872
> add without Cache parameter to getSchema

- src/client.js
- test/client.test.js
Addition of **x-request-id**  to SOAP requests
Jira - [NEO-90890](https://jira.corp.adobe.com/browse/NEO-90890)
The code change adds a new header x-request-id to every soap request , which allows us to better debug the requests that fail . We can refer the request id and check the corresponding metrics to debug the issue.
> NEO-90890 - Add request id to soap calls
